Styling the Landing Page
get-amigo/get-amigo.github.io pull request #3
Opened 2024-05-09 10:16 UTC by sruthin21

## What Does This PR Do??
This PR add's styling to the landing page

![Screenshot (386)](https://github.com/get-amigo/get-amigo.github.io/assets/125492105/b2e2531f-f617-4bae-8c7d-07c649318932)
![Screenshot (387)](https://github.com/get-amigo/get-amigo.github.io/assets/125492105/9a3e6a7a-9f24-4e1f-a7ab-21cfca54395f)
![Screenshot (388)](https://github.com/get-amigo/get-amigo.github.io/assets/125492105/b996dc47-9429-47ce-9e46-638ee72f25c5)
![Screenshot (389)](https://github.com/get-amigo/get-amigo.github.io/assets/125492105/307278b6-fea0-4a9f-a376-dcfeca074547)

2024-05-09 10:26 UTC, Bhaumik-Tandan requested changes

2024-05-09 10:26 UTC, Bhaumik-Tandan commented on package-lock.json
please remove this file we are using pnpm

2024-05-09 10:26 UTC, Bhaumik-Tandan commented on src/components/landing/nav.tsx
> +];
what is use of nav bar if it does not do anything

2024-05-09 10:39 UTC, Bhaumik-Tandan requested changes

2024-05-09 10:39 UTC, Bhaumik-Tandan commented on yarn.lock
There should be only one lock file in a project

2024-05-09 10:39 UTC, sruthin21 commented on src/components/landing/nav.tsx
> +];
> what is use of nav bar if it does not do anything

Ok Remove navigation And Navbar

2024-05-09 10:40 UTC, sruthin21 commented on yarn.lock
Lock File Means??

2024-05-09 10:43 UTC, sruthin21 commented on yarn.lock
Which lock file should be deleted

2024-05-09 10:43 UTC, Bhaumik-Tandan commented
please make a pr towards dev

2024-05-09 10:44 UTC, Bhaumik-Tandan commented on yarn.lock
both since we are using pnpn

2024-05-09 10:48 UTC, sruthin21 commented on yarn.lock
yarn.lock and package-lock.json Is this the two lock files

2024-05-09 10:54 UTC, sruthin21 commented
> please make a pr towards dev

how to make pr towards dev

2024-05-11 13:58 UTC, mrprince88 commented
We dont need any navigation and login buttons here @sruthin21. Can you remove these and also test for responsiveness.

Thanks

2024-05-13 08:56 UTC, closed without merging