update landing page design
get-amigo/get-amigo.github.io pull request #5
Opened 2024-05-09 11:39 UTC by amit-ksh

- Revamp the whole home page of the application
- Add navbar animation
- Add the new section **text reveal section**

[Preview](https://drive.google.com/file/d/1TWro7pLsskRdPTJIfizQRhLYXByKWLlL/view?usp=sharing)

2024-05-11 05:40 UTC, mrprince88 commented
@amit-ksh this looks good. Can you resolve the conflicts?

2024-05-11 06:36 UTC, amit-ksh commented
Done!

2024-05-11 13:54 UTC, Bhaumik-Tandan requested changes

2024-05-11 13:54 UTC, Bhaumik-Tandan commented on src/app/page.tsx
> +
please replace with some text

2024-05-11 14:09 UTC, mrprince88 commented
Can you remove the lorem ipsum text and also remove links from header. We dont need these

2024-05-12 19:59 UTC, amit-ksh commented
Updated the code as you said @mrprince88

2024-05-13 13:39 UTC, merged